runtime: custom
env: flex

resources:
  cpu: 4
  memory_gb: 6.5
  disk_size_gb: 10

liveness_check:
  path: "/liveness_check"
  timeout_sec: 4
  check_interval_sec: 60
  failure_threshold: 10

readiness_check:
  path: "/readiness_check"
  app_start_timeout_sec: 1200

